#include <18F4550.h>
#device ADC = 10
#USE DELAY(CLOCK=20000000)
#FUSES HS,NOWDT,NOPROTECT,NOPUT,MCLR=OFF,CPUDIV2
#USE STANDARD_IO (B)
#USE STANDARD_IO (C)
#USE STANDARD_IO (D)
#USE STANDARD_IO (A)
#USE RS232(BAUD=9600,XMIT=PIN_C6,RCV=PIN_C7,BITS=8,STOP=1,PARITY=N)

INT16 DATO = 0;
FLOAT DATO1;

VOID TEMPERATURA(){
SET_ADC_CHANNEL(0);
DELAY_MS(40);
DATO = READ_ADC();
DATO1 = DATO*1;
DELAY_MS(500);
PRINTF("%4.1F/r/n",DATO1);
}
void main(){
 setup_adc_ports(AN0);
 setup_adc(ADC_CLOCK_DIV_2);
   while(TRUE)
   {
      TEMPERATURA();
   }

}
